### ISSUE TITLE
No means to provide a redirect url after ending the session

### ISSUE THREAD

**Issue by jusefb** [oidcproxydotnet/OidcProxy.Net#173] opened 2024-04-11 21:18 UTC
**Description**

First of all thanks for a great library, I have managed to implement BFF in my app using it, keep up the great work. I am just having one issue with the logout procedure. Currently, there appears to be no way to specify a redirect URL after ending a session in OidcProxy.Net. This functionality is crucial for a seamless user experience, allowing users to be redirected to a specified page after they log out. I am using Auth0 with Angular 17.

**Expected Behavior**

After a user ends their session using the /.auth/end-session endpoint, the application should redirect them to a pre-defined URL. This is typically handled by providing a post_logout_redirect_uri parameter in the logout request.

**Current Behavior**

There is no parameter or method documented or available in OidcProxy.Net that supports specifying a redirect URL post-logout. When a session is ended, the user is not redirected, impacting the user flow and experience.

**Possible Solution**

Implement an option to specify a post_logout_redirect_uri as part of the logout process. This could be a configuration in the startup settings or as part of the logout URL query parameters.

**Steps to Reproduce**

- Configure OidcProxy.Net for an application.
- Attempt to end a session using /.auth/end-session.
- Observe that there is no redirection after the session ends.

**Comment by appie2go** [comment] 2024-04-12 02:11
Hi there,

Thanks for your feedback. I believe this issue is a duplicate of https://github.com/oidcproxydotnet/OidcProxy.Net/issues/123

Can you let me know if this provides a solution for you?

Thanks,

Albert

**Comment by jusefb** [comment] 2024-04-12 11:59
Thank you for pointing at the above issue, however, I don't see any way of providing a post redirect URL when using Auth0Proxy. Also in the provided example you pass "options" to the method, I cant seem to be able to figure out what object is expected in this options parameter:
`    o.RegisterIdentityProvider<IIdentityProvider, OpenIdConnectProviderWithRedirectUrl>(options);
`

**Comment by appie2go** [comment] 2024-04-24 11:55
Hi, 

Sorry for the late reply, i was traveling. 

I see. I will see if I can include your example in the auth0 demo because i believe it's a valid case. I'll see if I can make that happen before the end of the month.

Cheers, and thanks again for your feedback,

**Comment by spyder007** [comment] 2024-11-21 15:14
It looks as though Auth0 has changed their logout endpoints  The OidcProxy.Net.Auth0 library (specifically, `Auth0IdentityProvider`) is hardcoding `/oidc/logout` (line 57), which uses the `post_logout_redirect_uri` parameter (see [Log Users Out of Auth0 with OIDC Endpoint](https://auth0.com/docs/authenticate/login/logout/log-users-out-of-auth0)).  However, `Auth0IdentityProvider` is using `returnTo`. 

`returnTo` is a parameter on the `/v2/logout` endpoint in Auth0 (see [Redirect Users with Alternative Logout](https://auth0.com/docs/authenticate/login/logout/redirect-users-after-logout).

The quick fix would be to change the parameter from `returnTo` to `post_logout_redirect_uri`, but I am not sure which endpoint we should be using generally.

**Comment by appie2go** [comment] 2024-11-22 10:53
Yes, this "feature" needs a closer look anyways. Like you say, it would make sense to be more flexible there. Consumers should be able to choose between the different logout endpoints and to pass additional parameters..

Will look into it this month.

**Comment by appie2go** [comment] 2024-11-22 18:35
Hi!

You're welcome! And great to hear! That's why we started the project in the first place.

And by all means, please do feel free to create a pull request. If you want to get in touch with other people involved in the project, i just started a slack channel. Request access to it here: https://forms.gle/Cng3CFsPgwUKpdVc9

**Comment by spyder007** [comment] 2024-11-24 15:54
Created a PR (#333) but I didn't see any place to update documentation. I see the Wiki (although, admittedly, it took a minute for me to find that... I don't use the Github wiki that often), but cannot edit it.  Let me know what I can do to update the documentation.

**Comment by appie2go** [comment] 2024-11-25 08:31
Thanks a lot. Looks good.

I will try to write some unit tests for it tonight. At the latest, i'll incorporate it into the code by the end of this week.

Only I can update the wiki. (This is yet another project that needs my attention... I could sure use some more help ;-) ) Anways, for now, please mail the modifications to oidcproxy.net@gmail.com

Cheers! And thanks again!

**Comment by spyder007** [comment] 2024-11-25 23:55
Sent over some updates.

I can devote some time to help, maybe a quick chat to see what your current priorities are?  Let me know!

**Comment by appie2go** [comment] 2024-12-13 10:30
Released in 5.3.0.

Thanks, gentlemen! 

And sorry for the delay! :-)

**Closed by appie2go** 2024-12-13 10:30 UTC
